export const INSULTS = {
  "LOW": [
    "Did you forget to eat, or are you just practicing for hide-and-seek?",
    "You’ve got more bones than a skeleton convention!",
    "Blink, and you might disappear!",
    "Bro, are you on a diet or a hunger strike?",
    "You’re so light, a gust of wind might just carry you away!",
    "If you were any skinnier, you’d be a 2D character!",
    "Even your shadow is trying to gain weight!",
    "I’ve seen more meat on a toothpick!",
    "You must be on that air-and-sunlight diet!",
    "At least you won’t break the scale… or even register on it!",
    "If you turned sideways, you’d become invisible!",
    "I’ve seen more meat on a vegetarian’s plate!",
    "Did you lose a fight with a treadmill?",
    "Are you on a liquid diet… of just air?",
    "You’re so skinny, your spirit animal is a pencil!",
    "You make chopsticks look like drumsticks!",
    "Your body type is 'absent'!",
    "Even a gust of wind thinks twice about messing with you!",
    "When you step on the scale, it asks, ‘Are you a ghost?’",
    "You could slip through a keyhole, no cap!",
  ],
  "MID": [
    "You’re like Goldilocks—just the right amount of thicc!",
    "Walking the fine line between snack and full-course meal!",
    "Thicc enough to turn heads, slim enough to keep them!",
    "You’re what happens when comfy meets curvy!",
    "Not too much, not too little, you’re just right, fam!",
    "Thicc with purpose, keeping it balanced!",
    "You’ve got that perfect blend of thicc and fit!",
    "You’re rocking that healthy thiccness!",
    "Thicc, but still got the moves like Jagger!",
    "Just the right amount of cushion for the pushin’!",
    "Right in the Goldilocks zone—just right!",
    "You’ve unlocked the ‘perfectly balanced’ achievement!",
    "You’re like the default setting on a character creator—nice and average!",
    "Solid as a rock… but less Rocky and more Dwayne Johnson!",
    "Not too hot, not too cold… you’re just the right weight, Goldilocks!",
    "You’re what they call 'prime real estate'!",
    "If balance was an art, you’d be the Mona Lisa!",
    "You’re like a pizza with just the right amount of toppings—chef’s kiss!",
    "Fit enough for action, chill enough for snacks!",
    "Your weight’s got the perfect algorithm: no errors, just vibes!",
  ],
  "HIGH": [
    "Bruh, did you eat the gym?",
    "Looks like the only thing you’re lifting is donuts!",
    "You’re not just thick, you’re thicc with a double ‘c’!",
    "Even your shadow’s trying to slim down!",
    "Are those abs or did you just swallow a basketball?",
    "Time to turn those love handles into trophy handles!",
    "You’ve got more rolls than a bakery, fam!",
    "Not even gravity can hold you back… literally!",
    "You must be allergic to cardio, huh?",
    "Your scale just filed for retirement!",
    "Looks like you’re built for comfort, not speed!",
    "Your jeans have stretch marks, fam!",
    "Are you bulking, or is that just a permanent setting?",
    "You’re in shape… round is a shape, right?",
    "I see you’re carrying some extra ‘emotional support’ weight!",
    "When you sit around the house, you really sit around the house!",
    "You’re so big, you make the world go round… literally!",
    "Even your selfies come with a wide-angle lens!",
    "You have enough mass to start your own planet!",
    "I guess the buffet’s ‘all-you-can-eat’ sign was taken as a challenge?",
  ]
}